name: "Cancel TFE plan check for non-head commits"

on:
  pull_request:

jobs:
  cancel_plan:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python  
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        run: |
          python -m pip install --upgrade pip
          pip install terrasnek
